routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// add middleware => 'auth:admin'
Route::group(['namespace' => 'Admin'], function() {

    Route::get('admin/home', 'HomeController@index')->name('admin.home');

    // Advertise
    Route::resource('admin/advertise', 'AdvertiseController');

    // City
    Route::resource('admin/city', 'CityController');

    // Event
    Route::resource('admin/event', 'EventController');

    // Offer
    Route::resource('admin/offer', 'OfferController');

    // Place
    Route::resource('admin/place', 'PlaceController');

    // Prayer 
    Route::resource('admin/prayer', 'PrayerController');

    // Vendor
    Route::resource('admin/vendor', 'VendorController');

    // Category for cities
    Route::resource('admin/category','CategoryController');

    // Prayer Category
    Route::resource('admin/prayercategory', 'PrayerCategoryController');

    // Prayer sub Category
    Route::resource('admin/prayersubcategory','PrayerSubCategoryController');

    // Prayer Names
    Route::resource('admin/prayername','PrayerNameController');

    // Country
    Route::resource('admin/country', 'CountryController');

    // Permissions
    Route::resource('admin/permission','PermissionController');

    // Role
    Route::resource('admin/role', 'RoleController');

    // Admin user
    Route::resource('admin/user', 'UserController');

    // Admin Profile
    Route::get('admin/profile/{admin}','ProfileController@edit')->name('admin.profile');
    Route::patch('admin/profile-update/{admin}','ProfileController@update')->name('admin.profile-update');

    // Admin Auth routes
    Route::get('admin-login','Auth\LoginController@showLoginForm')->name('admin.login');

    // the name admin-login must be the same
    Route::post('admin-login', 'Auth\LoginController@login');



});


Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\City;
use App\Model\Admin\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CityController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cities = City::all();
        $countries = Country::all();
        return view('admin.city.index', compact('cities', 'countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $countries = Country::all();
        return view('admin.city.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(City $city)
    {
        //
        $this->validate(request(),[
            'name' => 'required',
            'image' => 'required',
            'country' => 'required',

        ]);

        $city->name = request('name');
        $city->country_id = request('country');
        $city->image = request('image')->store('public/images');
        $city->save();

        return redirect(route('city.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $city = City::where('id', $id)->first();
        $countries = Country::all();
        $cities = City::all();
        return view('admin.city.edit', compact('city', 'countries','cities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(City $city)
    {
        //
        $this->validate(request(), [
            'name'=> 'required',
        ]);


        $city->name = request('name');
        $city->country_id = request('country');

        if (request()->hasFile('image') != null) {
            $city->image = request('image')->store('public/images');
        }

        $city->update();


        return redirect(route('city.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        City::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/city/create.blade.php
@extends('admin.layouts.app')

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Hamlatik
            <small>Cities</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Forms</a></li>
            <li class="active">Editors</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">Cities Section</h3>
                    </div>
                    @include('includes.messages')
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('city.store') }}" method="POST" enctype="multipart/form-data" >
                        {{ csrf_field() }}
                        <div class="box-body">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="title">City Name</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">
                                </div>

                                <div class="form-group">
                                    <label for="image">City Image</label>
                                    <input type="file" name="image" id="image">
                                    <p class="help-block">Image must be less than 150kb</p>
                                </div>

                                <div class="form-group">
                                    <label for="">Add Country </label>
                                    <select name="country" id="" class="form-control">
                                        @foreach($countries as $country)
                                            <option value="{{ $country->id }}">{{ $country->name }}</option>
                                        @endforeach
                                    </select>
                                </div>


                              <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                          </div>
                        </div> <!-- box-body  -->
                </form>
            </div>
        </div>
        <!-- /.col-->
</div>
<!-- ./row -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->


@endsection

resources/views/admin/city/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Hamlatik
                <small>Cities</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="box box-success">
                        <div class="box-header with-border">
                            <h3 class="box-title">Titles</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('city.update', $city->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="box-body">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="title">City Name</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" value="{{ $city->name }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="image">City Image</label>
                                        <input type="file" name="image" id="image">
                                        <p class="help-block">Image must be less than 150kb</p>
                                    </div>

                                    <div class="form-group">
                                        <label for="">Add Country </label>
                                        <select name="country" id="" class="form-control">
                                            @foreach($cities as $city)
                                                @foreach($countries as $country)
                                                    @if($city->country_id == $country->id)
                                                <option value="{{ $country->id }}">{{ $country->name }}</option>
                                                    @endif
                                                    @endforeach
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                        <a type="button" class="btn btn-warning " href="{{ route('admin.home') }}">Back</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/city/index.blade.php
@extends('admin.layouts.app')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection

@section('main-content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Blank page
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('City List') }}</h3>
                    <a class="btn btn-success" href="{{ route('city.create') }}">{{ __('Add City') }}</a>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Data Table With Full Features</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body table-responsive">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>City</th>
                                    <th>Country</th>
                                    <th>Image</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($cities as $city)

                                    <tr>
                                        <td>{{ $loop->index + 1 }}</td>
                                        <td>{{ $city->name }}</td>
                                        <td>
                                            @foreach($countries as $country)

                                                @if($city->country_id == $country->id)
                                                    {{ $country->name }}
                                                @endif
                                                @endforeach
                                        </td>
                                        <td><img src="{{ Storage::disk('local')->url($city->image) }}" height="100px" width="100px" alt=""></td>
                                        <td><a href="{{ route('city.edit', $city->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                                        <td>
                                            <form method="post" id="delete-form-{{$city->id}}" action="{{ route('city.destroy', $city->id) }}">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>

                                            <a href="" onclick="
                                                    if (confirm('Are you sure, you want to delete this?')){
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{$city->id}}').submit();
                                                    } else {
                                                    event.preventDefault();
                                                    }

                                                    ">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </a>

                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>S.No</th>
                                    <th>City</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


@endsection


@section('footerSection')

            <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
            <script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

            <script>
                $(function (){
                    $("#example1").DataTable();
                    $('#example2').DataTable({
                        "paging":true,
                        "lengthChange":false,
                        "searching":false,
                        "ordering": true,
                        "info": true,
                        "autoWidth": false
                    });
                });
            </script>

@endsection