routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// add middleware => 'auth:admin'
Route::group(['namespace' => 'Admin'], function() {

    Route::get('admin/home', 'HomeController@index')->name('admin.home');

    // Advertise
    Route::resource('admin/advertise', 'AdvertiseController');

    // City
    Route::resource('admin/city', 'CityController');

    // Event
    Route::resource('admin/event', 'EventController');

    // Offer
    Route::resource('admin/offer', 'OfferController');

    // Place
    Route::resource('admin/place', 'PlaceController');

    // Prayer 
    Route::resource('admin/prayer', 'PrayerController');

    // Vendor
    Route::resource('admin/vendor', 'VendorController');

    // Category for cities
    Route::resource('admin/category','CategoryController');

    // Prayer Category
    Route::resource('admin/prayercategory', 'PrayerCategoryController');

    // Prayer sub Category
    Route::resource('admin/prayersubcategory','PrayerSubCategoryController');

    // Prayer Names
    Route::resource('admin/prayername','PrayerNameController');

    // Country
    Route::resource('admin/country', 'CountryController');

    // Permissions
    Route::resource('admin/permission','PermissionController');

    // Role
    Route::resource('admin/role', 'RoleController');

    // Admin user
    Route::resource('admin/user', 'UserController');

    // Admin Profile
    Route::get('admin/profile/{admin}','ProfileController@edit')->name('admin.profile');
    Route::patch('admin/profile-update/{admin}','ProfileController@update')->name('admin.profile-update');

    // Admin Auth routes
    Route::get('admin-login','Auth\LoginController@showLoginForm')->name('admin.login');

    // the name admin-login must be the same
    Route::post('admin-login', 'Auth\LoginController@login');



});


Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/AdvertiseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\Advertise;
use Faker\Provider\Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use phpDocumentor\Reflection\File;


class AdvertiseController extends Controller
{

    public function __construct()
    {
         $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $advertises = Advertise::all();
        return view('admin.advertise.index', compact('advertises'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.advertise.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
//       $this->validate($request, [
//
//           'name' => 'required',
//           'mobile' => 'required',
//
//       ]);


//       $inputs = $request->all();
//
//       if ($file = $request->file('image')) {
//           $name = $file->getClientOriginalName();
//           $file->move('public/images', $name);
//           $inputs['images'] = $name;
//       }
//
//       Advertise::create($inputs);

        if ($request->hasFile('image')) {
        $advertiseImage =  $request->image->store('public/images');
    }

//        if ($request->hasFile('image')) {
//
//            $image = $request->file('image');
//            $advertiseImage = time() . '.' . $image->getClientOriginalName();
//            Image::make($image)->resize(300,300)->save(storage_path('public/images' . $advertiseImage));
//
//        }

        $advertise = new Advertise;

        $advertise->image = $advertiseImage;
       $advertise->name     = $request->name;
       $advertise->mobile   = $request->mobile;
       $advertise->snapchat = $request->snapchat;
       $advertise->instegram = $request->instegram;
       $advertise->twitter = $request->twitter;
       $advertise->facebook = $request->facebook;
       $advertise->latitude = $request->latitude;
       $advertise->longitude = $request->longitude;

       $advertise->save();

       return redirect(route('advertise.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $advertise = Advertise::where('id', $id)->first();
        return view('admin.advertise.edit', compact('advertise'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'name',
            'mobile',

        ]);

        $advertise = Advertise::find($id);

        if ($request->hasFile('image') != null) {
         $advertiseImage = $request->image->store('public/images');
            $advertise->image        =  $advertiseImage;
        }


        $advertise->name        = $request->name;
        $advertise->mobile      = $request->mobile;
        $advertise->snapchat    = $request->snapchat;
        $advertise->instegram   = $request->instegram;
        $advertise->twitter     = $request->twitter;
        $advertise->facebook    = $request->facebook;
        $advertise->latitude    = $request->latitude;
        $advertise->longitude    = $request->longitude;

        $advertise->save();

        return redirect(route('advertise.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Advertise::where('id',$id)->delete();

        redirect()->back();

    }
}

resources/views/admin/advertise/create.blade.php
@extends('admin.layouts.app')


@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Hamlat
            <small>Hamlat</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Forms</a></li>
            <li class="active">Editors</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">Titles</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('advertise.store') }}" enctype="multipart/form-data">
                        <div class="box-body">

                            {{ csrf_field() }}

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="title">Ads Name</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">
                                </div>


                              <div class="form-group">
                                <label for="sub title">Mobile</label>
                                <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Enter Mobile">
                              </div>

                            <div class="form-group">
                                    <label for="slug"> Snapchat </label>
                                    <input type="text" class="form-control" id="snapchat" name="snapchat" placeholder="Enter snapchat url">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Instegram </label>
                              <input type="text" class="form-control" id="instegram" name="instegram" placeholder="Enter instegram url">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Twitter </label>
                              <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Enter Twitter url">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Snapchat </label>
                              <input type="text" class="form-control" id="facebook" name="facebook" placeholder="Enter facebook url">
                            </div>

                            <div class="form-group">
                              <label for="slug"> hamlah latitude location </label>
                              <input type="text" step="any" class="form-control" id="latitude" name="latitude" placeholder="Enter latitude">
                            </div>

                            <div class="form-group">
                              <label for="slug"> hamlah longitude location </label>
                              <input type="text" step="any" class="form-control" id="longitude" name="longitude" placeholder="Enter longitude">
                            </div>


                            <div class="form-group">
                              <label for="image">File input</label>
                              <input type="file" name="image" id="image">
                              <p class="help-block">image size must be less than 300kb</p>
                            </div>

                              <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </div>
                          </div>
                        </div> <!-- box-body  -->
                    </form>
                </div> <!-- box primary  -->
            </div>  <!-- /.col-->
        </div>  <!-- ./row -->
    </section> <!-- /.content -->
</div> <!-- /.content-wrapper -->



@endsection

resources/views/admin/advertise/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Hamlat
            <small>Hamlat</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Forms</a></li>
            <li class="active">Editors</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">Titles</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('advertise.update', $advertise->id) }}" enctype="multipart/form-data">
                        <div class="box-body">

                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="title">Ads Name</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" value="{{ $advertise->name }}">
                                </div>


                              <div class="form-group">
                                <label for="sub title">Mobile</label>
                                <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Enter Mobile" value="{{ $advertise->mobile }}">
                              </div>

                            <div class="form-group">
                                    <label for="slug"> Snapchat </label>
                                    <input type="text" class="form-control" id="snapchat" name="snapchat" placeholder="Enter snapchat url" value="{{ $advertise->snapchat }}">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Instegram </label>
                              <input type="text" class="form-control" id="instegram" name="instegram" placeholder="Enter instegram url" value="{{ $advertise->instegram }}">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Twitter </label>
                              <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Enter Twitter url" value="{{ $advertise->twitter }}">
                            </div>

                            <div class="form-group">
                              <label for="slug"> Facebook </label>
                              <input type="text" class="form-control" id="facebook" name="facebook" placeholder="Enter facebook url" value="{{ $advertise->facebook }}">
                            </div>

                            <div class="form-group">
                              <label for="slug"> hamlah latitude location </label>
                              <input type="text" class="form-control" id="latitude" name="latitude" placeholder="Enter latitude" value="{{ $advertise->latitude }}">
                            </div>

                            <div class="form-group">
                              <label for="slug"> hamlah longitude location </label>
                              <input type="text" class="form-control" id="longitude" name="longitude" placeholder="Enter longitude" value="{{ $advertise->longitude }}">
                            </div>


                            <div class="form-group">
                              <label for="image">File input</label>
                              <input type="file" name="image" id="image">
                              <p class="help-block">Example block-level help text here.</p>
                                <img class="img-responsive" width="150" height="150" src="{{ Storage::disk('local')->url($advertise->image) }}" alt="">
                            </div>

                              <div class="form-group">
                                <button type="submit" class="btn btn-success">Submit</button>
                                  <a  class="btn btn-warning" href="{{ route('advertise.index') }}">Back</a>
                                </div>

                            </div>
                          </div>
                        </div> <!-- box-body  -->
                    </form>
                </div> <!-- box primary  -->
            </div>  <!-- /.col-->
        </div>  <!-- ./row -->
    </section> <!-- /.content -->
</div> <!-- /.content-wrapper -->


@endsection

resources/views/admin/advertise/index.blade.php
@extends('admin.layouts.app')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection

@section('main-content')


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Blank page
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Title</h3>
                    <a type="button" class="btn btn-success" href="{{ route('advertise.create') }}">Add Advertise</a>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body table-responsive">
                    <table id="example1" class="table table-bordered table-striped">

                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Name</th>
                            <th>Mobile</th>
                            <th>image</th>
                            <th>Edit</th>
                            <th>Delete</th>

                        </tr>
                        </thead>
                        <tbody>

                        @foreach($advertises as $advertise)

                            <tr>
                                <td>{{ $loop->index + 1 }}</td>
                                <td>{{ $advertise->name }}</td>
                                <td>{{ $advertise->mobile }}</td>
                                <td><img class="img-responsive" height="150" width="150" src="{{Storage::disk('local')->url($advertise->image)}} " alt=""></td>
                                <td><a href="{{ route('advertise.edit', $advertise->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                                <td>

                                    <form method="post" id="delete-form-{{ $advertise->id }}" action="{{ route('advertise.destroy', $advertise->id) }}" style="display: none" >

                                        {{ csrf_field() }}

                                        {{ method_field('DELETE') }}

                                    </form>

                                    <a href="" onclick="
                                            if (confirm('Are you sure, you want to delete this?')){
                                            event.preventDefault();
                                            document.getElementById('delete-form-{{$advertise->id}}').submit();
                                            } else {
                                            event.preventDefault();
                                            }
                                            ">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>S.No</th>
                            <th>Name</th>
                            <th>Mobile</th>
                            <th>image</th>
                            <td>Edit</td>
                            <td>Delete</td>

                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        Footer
    </div>
    <!-- /.box-footer-->
    </div>
    <!-- /.box -->

    </section>
    <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


@endsection


@section('footerSection')

    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js')  }}"></script>
    <script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $(function (){
           $("#example1").DataTable();
           $('#example2').DataTable({
              "paging": true,
               "lengthChange": false,
               "searching": false,
               "ordering": true,
               "info": true,
               "autoWidth": false
           });
        });

    </script>

@endsection