routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// add middleware => 'auth:admin'
Route::group(['namespace' => 'Admin'], function() {

    Route::get('admin/home', 'HomeController@index')->name('admin.home');

    // Advertise
    Route::resource('admin/advertise', 'AdvertiseController');

    // City
    Route::resource('admin/city', 'CityController');

    // Event
    Route::resource('admin/event', 'EventController');

    // Offer
    Route::resource('admin/offer', 'OfferController');

    // Place
    Route::resource('admin/place', 'PlaceController');

    // Prayer 
    Route::resource('admin/prayer', 'PrayerController');

    // Vendor
    Route::resource('admin/vendor', 'VendorController');

    // Category for cities
    Route::resource('admin/category','CategoryController');

    // Prayer Category
    Route::resource('admin/prayercategory', 'PrayerCategoryController');

    // Prayer sub Category
    Route::resource('admin/prayersubcategory','PrayerSubCategoryController');

    // Prayer Names
    Route::resource('admin/prayername','PrayerNameController');

    // Country
    Route::resource('admin/country', 'CountryController');

    // Permissions
    Route::resource('admin/permission','PermissionController');

    // Role
    Route::resource('admin/role', 'RoleController');

    // Admin user
    Route::resource('admin/user', 'UserController');

    // Admin Profile
    Route::get('admin/profile/{admin}','ProfileController@edit')->name('admin.profile');
    Route::patch('admin/profile-update/{admin}','ProfileController@update')->name('admin.profile-update');

    // Admin Auth routes
    Route::get('admin-login','Auth\LoginController@showLoginForm')->name('admin.login');

    // the name admin-login must be the same
    Route::post('admin-login', 'Auth\LoginController@login');



});


Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>

	@include('admin.layouts.head')

</head>
<body class="hold-transition skin-green-light sidebar-mini">

<div class="wrapper">

  @include('admin.layouts.header')

  @include('admin.layouts.sidebar')

  @section('main-content')

  @show

  @include('admin.layouts.footer')


</div>


</body>
</html>

resources/views/admin/layouts/footer.blade.php
 <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.8
    </div>
    <strong>Copyright &copy; 2016-{{ \Carbon\Carbon::now()->year }} <a href="http://cmp-engineers.com">CMP Engineers</a>.</strong> All rights
    reserved.
  </footer>

  <!-- jQuery 2.2.3 -->
  <script src="{{ asset('admin/plugins/jQuery/jquery-2.2.3.min.js') }} "></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="  https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
  $.widget.bridge('uibutton', $.ui.button);
  </script>
  <!-- Bootstrap 3.3.6 -->
  <script src=" {{ asset('admin/bootstrap/js/bootstrap.min.js') }}"></script>
  <!-- Morris.js charts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src=" {{ asset('admin/plugins/morris/morris.min.js') }} "></script>
  <!-- Sparkline -->
  <script src=" {{ asset('admin/plugins/sparkline/jquery.sparkline.min.js') }} "></script>
  <!-- jvectormap -->
  <script src=" {{ asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }} "></script>
  <script src=" {{ asset('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }} "></script>
  <!-- jQuery Knob Chart -->
  <script src=" {{ asset('admin/plugins/knob/jquery.knob.js') }} "></script>
  <!-- daterangepicker -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
  <script src=" {{ asset('admin/plugins/daterangepicker/daterangepicker.js') }} "></script>
  <!-- datepicker -->
  <script src=" {{ asset('admin/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src=" {{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }} "></script>
  <!-- Slimscroll -->
  <script src=" {{ asset('admin/plugins/slimScroll/jquery.slimscroll.min.js') }} "></script>
  <!-- FastClick -->
  <script src=" {{  asset('admin/plugins/fastclick/fastclick.js') }} "></script>
  <!-- AdminLTE App -->
  <script src=" {{ asset('admin/dist/js/app.min.js') }} "></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{--  <script src=" {{ asset('admin/dist/js/pages/dashboard.js') }} "></script>--}}
  <!-- AdminLTE for demo purposes -->
  <script src=" {{ asset('admin/dist/js/demo.js') }}"></script>

 @section('footerSection')

   @show

resources/views/admin/layouts/head.blade.php
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>Hamlatik</title>
  <!-- Tell the browser to be responsive to screen width -->
  <link rel="stylesheet" href="{{ asset('admin/bootstrap/css/bootstrap.min.css') }}">

  <link rel="stylesheet" href=" {{ asset('https://use.fontawesome.com/releases/v5.8.1/css/all.css') }} " integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')}}">

  <!-- Ionicons -->
  <link rel="stylesheet" href= "{{ asset('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href= "{{ asset('admin/dist/css/AdminLTE.min.css') }}" >
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css')}}" >
  <!-- iCheck -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/iCheck/flat/blue.css') }}">
  <!-- Morris chart -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/morris/morris.css') }} ">
  <!-- jvectormap -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css')  }}">
  <!-- Date Picker -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/datepicker/datepicker3.css') }} ">
  <!-- Daterange picker -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/daterangepicker/daterangepicker.css') }} ">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href=" {{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }} ">

  @section('headSection')

    @show


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>{{ __('Hamlatik') }}</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src=" {{ asset('admin/dist/img/hamlatik-logo.png') }} " class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ __('Hamlatik') }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src=" {{  asset('admin/dist/img/hamlatik-logo.png') }}" class="img-circle" alt="User Image">

                            <p>
                                {{   Auth::user()->name }}

                                {{--                  <small>Member since {{ Auth::user()->created_at->toFormattedDataString() }}</small>--}}
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.profile', Auth::user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right btn btn-default btn-flat">
                                <a href="{{ route('logout') }}" onclick="

                event.preventDefault();
                document.getElementById('logout-form').submit();


                ">{{ __('Logout') }}</a>
                                <form id="logout-form" method="POST" action="{{ route('logout') }}">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/pageHead.blade.php
<h1>
    Hamlatik
    <small>lets create something</small>
</h1>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src=" {{ asset('admin/dist/img/hamlatik-logo.png') }} " class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Hamlatik.com</p>

            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Offer</span>
                    <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="{{ route('offer.create') }}"><i class="fa fa-circle-o"></i> Add Offer</a></li>
                    <li><a href=" {{ route('offer.index') }} "><i class="fa fa-circle-o"></i> View Offers</a></li>
                </ul>
            </li>

            <li class=" treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Vendor</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    @can('vendors.admin', Auth::user())
                        <li class="active"><a href="{{  route('vendor.create') }}"><i class="fa fa-circle-o"></i> Add Vendor</a></li>
                    @endcan
                    <li><a href="{{ route('vendor.index') }}"><i class="fa fa-circle-o"></i> View Vendors</a></li>

                </ul>
            </li>


            @can('vendors.admin', Auth::user())

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Admin</span>
                        <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('user.create') }}"><i class="fa fa-circle-o"></i> Add Admin</a></li>
                        <li><a href="{{ route('user.index') }}"><i class="fa fa-circle-o"></i> View Admins</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Role</span>
                        <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('role.create') }}"><i class="fa fa-circle-o"></i> Add Role</a></li>
                        <li><a href="{{ route('role.index') }}"><i class="fa fa-circle-o"></i> View Roles</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Permission</span>
                        <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('permission.create') }}"><i class="fa fa-circle-o"></i> Add Permission</a></li>
                        <li><a href="{{ route('permission.index') }}"><i class="fa fa-circle-o"></i> View Permissions</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Advertise</span>
                        <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('advertise.create') }}"><i class="fa fa-circle-o"></i> Add Ads</a></li>
                        <li><a href="{{ route('advertise.index') }}"><i class="fa fa-circle-o"></i> View Advertise</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-calendar-minus-o"></i> <span>Event</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('event.create') }}"><i class="fa fa-circle-o"></i> Add Event</a></li>
                        <li><a href="{{ route('event.index') }}"><i class="fa fa-circle-o"></i> View Event</a></li>
                    </ul>
                </li>



                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-tripadvisor"></i> <span>Place</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('place.create') }}"><i class="fa fa-circle-o"></i> Add Place</a></li>
                        <li><a href="{{ route('place.index') }}"><i class="fa fa-circle-o"></i> View places</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Prayer Name</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('prayername.create') }}"><i class="fa fa-circle-o"></i> Add Prayer name</a></li>
                        <li><a href="{{ route('prayername.index') }}"><i class="fa fa-circle-o"></i> View prayers names</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Prayer Category</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('prayercategory.create') }}"><i class="fa fa-circle-o"></i> Add Prayer Category </a></li>
                        <li><a href="{{ route('prayercategory.index') }}"><i class="fa fa-circle-o"></i> View prayers Categories</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Prayer Sub Category</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('prayersubcategory.create') }}"><i class="fa fa-circle-o"></i> Add Prayer Sub Category</a></li>
                        <li><a href="{{ route('prayersubcategory.index') }}"><i class="fa fa-circle-o"></i> View prayers sub Categories</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Prayer</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('prayer.create') }}"><i class="fa fa-circle-o"></i> Add Prayer</a></li>
                        <li><a href="{{ route('prayer.index') }}"><i class="fa fa-circle-o"></i> View prayers</a></li>
                    </ul>
                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-flag"></i> <span>Country</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('country.create') }}"><i class="fa fa-circle-o"></i> Add Country</a></li>
                        <li><a href=" {{ route('country.index') }}"><i class="fa fa-circle-o"></i> View Countries</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>City</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('city.create') }}"><i class="fa fa-circle-o"></i> Add City</a></li>
                        <li><a href=" {{ route('city.index') }}"><i class="fa fa-circle-o"></i> View cities</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Category</span>
                        <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{{ route('category.create') }}"><i class="fa fa-circle-o"></i> Add Category</a></li>
                        <li><a href="{{ route('category.index') }}"><i class="fa fa-circle-o"></i> View Categories</a></li>
                    </ul>
                </li>
            @endcan
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>