routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// add middleware => 'auth:admin'
Route::group(['namespace' => 'Admin'], function() {

    Route::get('admin/home', 'HomeController@index')->name('admin.home');

    // Advertise
    Route::resource('admin/advertise', 'AdvertiseController');

    // City
    Route::resource('admin/city', 'CityController');

    // Event
    Route::resource('admin/event', 'EventController');

    // Offer
    Route::resource('admin/offer', 'OfferController');

    // Place
    Route::resource('admin/place', 'PlaceController');

    // Prayer 
    Route::resource('admin/prayer', 'PrayerController');

    // Vendor
    Route::resource('admin/vendor', 'VendorController');

    // Category for cities
    Route::resource('admin/category','CategoryController');

    // Prayer Category
    Route::resource('admin/prayercategory', 'PrayerCategoryController');

    // Prayer sub Category
    Route::resource('admin/prayersubcategory','PrayerSubCategoryController');

    // Prayer Names
    Route::resource('admin/prayername','PrayerNameController');

    // Country
    Route::resource('admin/country', 'CountryController');

    // Permissions
    Route::resource('admin/permission','PermissionController');

    // Role
    Route::resource('admin/role', 'RoleController');

    // Admin user
    Route::resource('admin/user', 'UserController');

    // Admin Profile
    Route::get('admin/profile/{admin}','ProfileController@edit')->name('admin.profile');
    Route::patch('admin/profile-update/{admin}','ProfileController@update')->name('admin.profile-update');

    // Admin Auth routes
    Route::get('admin-login','Auth\LoginController@showLoginForm')->name('admin.login');

    // the name admin-login must be the same
    Route::post('admin-login', 'Auth\LoginController@login');



});


Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\Admin;
use App\Model\Admin\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = Admin::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $roles = Role::all();
        return view('admin.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [

            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:admins',
            'phone' => 'required|numeric|min:8',
            'password' => 'required|string|min:6|confirmed',

        ]);

        $request['password'] = bcrypt($request->password);

        $admin = Admin::create($request->all());
        $admin->roles()->sync($request->role);

        return redirect(route('user.index'))->with('message', 'admin Hamlah has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $user)
    {
        //
        $roles = Role::all();
        return view('admin.user.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $admin = Admin::find($id);

        $admin->password = bcrypt($request->password);
        $admin->name = $request->name;
        $admin->phone = $request->phone;
        $admin->email = $request->email;
        $admin->status  = $request->status;

        if ($admin->status == null)
        {
            $admin->status =  0;
        }

        $admin->update();

        $admin->roles()->sync($request->role);

        return redirect(route('user.index'))->with('message','Admin user has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Admin::where('id', $id)->delete();
        return redirect()->back()->with('message','Admin user deleted successfully ');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Text Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Add Admin</h3>
                        </div>

                    @include('includes.messages')
                    <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('user.store') }}">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="col-lg-12 ">

                                    <div class="form-group">
                                        <label for="title">username</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter user name" value="{{ old('name') }}">
                                    </div>


                                    <div class="form-group">
                                        <label for="sub title">Email</label>
                                        <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ old('email') }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">phone</label>
                                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Mobile number" value="{{ old('phone') }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" value="{{ old('password') }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="confirm password">Confirm Password</label>
                                        <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Confirm Password">
                                    </div>

                                    <div class="form-group">
                                        <label for=status">Status</label>
                                        <div class="checkbox">
                                            <label for="roles"><input type="checkbox" name="status" @if(old('status') == 1)
                                                checked
                                                                      @endif value="1">{{ __('Status') }}</label>
                                        </div>
                                    </div>

                                </div>


                                <div class="form-group">
                                    <label for="roles">Assign Role</label>
                                    <div class="rows">
                                        @foreach($roles as $role)

                                            <div class="col-lg-3">
                                                <div class="checkbox">
                                                    <label for="roles"><input type="checkbox" name="role[]" value="{{ $role->id }}">{{ $role->name }}</label>
                                                </div>
                                            </div>

                                        @endforeach
                                    </div>
                                </div>


                            </div>

                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a type="button" class="btn btn-warning" href="{{ route('user.index') }}">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Text Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Update Admin</h3>
                        </div>

                    @include('includes.messages')
                    <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('user.update', $user->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="box-body">
                                <div class="col-lg-12 ">

                                    <div class="form-group">
                                        <label for="title">username</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter user name" value="@if(old('name')){{ old('name') }}@else{{ $user->name }}@endif">
                                    </div>
                                    <div class="form-group">
                                        <label for="sub title">Email</label>
                                        <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" value="@if(old('email')){{old('email')}}@else{{$user->email}}@endif">
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">phone</label>
                                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Mobile number" value="@if(old('phone')){{ old('phone')}}@else{{$user->phone}}@endif">
                                    </div>

                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" >
                                    </div>

                                    <div class="form-group">
                                        <label for="confirm password">Confirm Password</label>
                                        <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Confirm Password">
                                    </div>



                                    <div class="form-group">
                                        <label for=status">Status</label>
                                        <div class="checkbox">
                                            <label for="roles"><input type="checkbox" name="status"
                                                                      @if(old('status') == 1 || $user->status == 1)
                                                                      checked
                                                                      @endif value="1">
                                                {{ __('Status') }}
                                            </label>
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label for="roles">Assign Role</label>
                                    <div class="rows">
                                    @foreach($roles as $role)
                                        <!-- user means here as admin and roles is the function inside model admin -->
                                            <div class="col-lg-3">
                                                <div class="checkbox">
                                                    <label for="roles"><input type="checkbox" name="role[]" value="{{ $role->id }}"

                                                                              @foreach($user->roles as $user_role)
                                                                              @if($user_role->id == $role->id)
                                                                              checked
                                                                @endif
                                                                @endforeach
                                                        >{{ $role->name }}</label>
                                                </div>
                                            </div>

                                        @endforeach
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a type="button" class="btn btn-warning" href="{{ route('user.index') }}">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

 @endsection

@section('main-content')


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">

            @include('admin.layouts.pageHead')

            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Admin users</h3>

                    @include('includes.messages')

                    <a class="col-lg-offset-0 btn btn-success" href="{{ route('user.create') }}">Add New user</a>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">

                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Data Table With Full Features</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body table-responsive">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>User</th>
                                    <th>Assigned Roles</th>
                                    <th>Status</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($users as $user)

                                    <tr>
                                        <td>{{ $loop->index + 1 }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td> <!-- this roles comes from the Admin model  -->
                                            @foreach($user->roles as $role)
                                                {{$role->name}},
                                            @endforeach
                                        </td>
                                        <td>{{ $user->status ? 'Active' : 'Not Active' }}</td>
                                        <td><a href="{{ route('user.edit', $user->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                                        <td>
                                            <form method="post" id="delete-form-{{ $user->id }}" action="{{ route('user.destroy', $user->id) }}" style="display: none">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                            <a href="" onclick="
                                                    if (confirm('Are you sure, you want to delete this? ')){
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{$user->id}}').submit();
                                                    } else {

                                                    event.preventDefault();
                                                    }

                                                    ">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>S.No</th>
                                    <th>User</th>
                                    <th>Assigned Roles</th>
                                    <th>Status</th>
                                    <th>Edit</th>
                                    <th>Delete</th>

                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

@section('footerSection')

    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"> </script>

    @endsection